name: DeepCIP_pytorch
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.6.15=py38h06a4308_0
  - cffi=1.15.1=py38h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - cryptography=37.0.1=py38h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hecacb30_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.23.1=py38h6c91a56_0
  - numpy-base=1.23.1=py38ha15fc14_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1q=h7f8727e_0
  - pillow=9.2.0=py38hace64e9_1
  - pip=22.1.2=py38h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.8=hdb3f193_5
  - pytorch=1.12.1=py3.8_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py38h06a4308_0
  - setuptools=63.4.1=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py38_cu113
  - torchvision=0.13.1=py38_cu113
  - typing_extensions=4.3.0=py38h06a4308_0
  - urllib3=1.26.11=py38h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.2.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - argparse==1.4.0
    - astor==0.8.1
    - async-timeout==4.0.2
    - attrs==22.1.0
    - cachetools==5.2.0
    - cloudpickle==2.1.0
    - colorama==0.4.5
    - contextlib2==21.6.0
    - filelock==3.8.0
    - frozenlist==1.3.1
    - fsspec==2022.7.1
    - future==0.18.2
    - google-auth==2.11.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - hyperopt==0.1.2
    - importlib-metadata==4.12.0
    - jinja2==3.1.2
    - joblib==1.1.0
    - json-tricks==3.15.5
    - markdown==3.4.1
    - markupsafe==2.1.1
    - multidict==6.0.2
    - networkx==2.8.6
    - nni==2.8
    - oauthlib==3.2.0
    - packaging==21.3
    - pandas==1.4.3
    - prettytable==3.3.0
    - protobuf==3.19.4
    - psutil==5.9.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.2
    - pymongo==4.2.0
    - pyparsing==3.0.9
    - pysnooper==1.1.1
    - python-dateutil==2.8.2
    - pythonwebhdfs==0.2.3
    - pytorch-lightning==1.7.3
    - pytz==2022.2.1
    - pyyaml==6.0
    - requests-oauthlib==1.3.1
    - responses==0.21.0
    - rsa==4.9
    - schema==0.7.5
    - scikit-learn==1.1.2
    - scipy==1.9.0
    - simplejson==3.17.6
    - sklearn==0.0
    - tensorboard==2.10.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - torch-cluster==1.6.0
    - torch-geometric==2.1.0.post1
    - torch-scatter==2.0.9
    - torch-sparse==0.6.15
    - torchmetrics==0.9.3
    - torchsnooper==0.8
    - tqdm==4.64.0
    - typeguard==2.13.3
    - wcwidth==0.2.5
    - websockets==10.3
    - werkzeug==2.2.2
    - yarl==1.8.1
    - zipp==3.8.1
prefix: /opt/conda/envs/DeepCIP_pytorch
